"""ARGOS design tokens as Python constants.

This file is generated from design-system/tokens.json. Do not edit by hand. Re-run `uv run python scripts/build_tokens.py` after any token change.
"""

from __future__ import annotations

from typing import Final

COLOR_GREEN_50: Final[str] = "#ecfdf5"
COLOR_GREEN_100: Final[str] = "#d1fae5"
COLOR_GREEN_400: Final[str] = "#34d399"
COLOR_GREEN_500: Final[str] = "#10b981"
COLOR_GREEN_600: Final[str] = "#059669"
COLOR_GREEN_700: Final[str] = "#047857"
COLOR_GREEN_900: Final[str] = "#064e3b"
COLOR_INK_50: Final[str] = "#f9fafb"
COLOR_INK_100: Final[str] = "#f3f4f6"
COLOR_INK_200: Final[str] = "#e5e7eb"
COLOR_INK_300: Final[str] = "#d1d5db"
COLOR_INK_400: Final[str] = "#9ca3af"
COLOR_INK_500: Final[str] = "#6b7280"
COLOR_INK_700: Final[str] = "#374151"
COLOR_INK_800: Final[str] = "#1f2937"
COLOR_INK_900: Final[str] = "#111827"
COLOR_INK_950: Final[str] = "#030712"
COLOR_PAPER: Final[str] = "#ffffff"
COLOR_NIGHT: Final[str] = "#0a0e17"
COLOR_MIDNIGHT: Final[str] = "#1a1a2e"
COLOR_SEVERITY_CRITICAL: Final[str] = "#7030A0"
COLOR_SEVERITY_HIGH: Final[str] = "#E53E3E"
COLOR_SEVERITY_MEDIUM: Final[str] = "#F6AD55"
COLOR_SEVERITY_LOW: Final[str] = "#F6E05E"
COLOR_SEVERITY_INFO: Final[str] = "#C6F6D5"
TYPOGRAPHY_FAMILY_SANS: Final[str] = "Inter, ui-sans-serif, system-ui, -apple-system, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif"
TYPOGRAPHY_FAMILY_MONO: Final[str] = ""JetBrains Mono", ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace"
TYPOGRAPHY_SIZE_XS: Final[str] = "0.75rem"
TYPOGRAPHY_SIZE_SM: Final[str] = "0.875rem"
TYPOGRAPHY_SIZE_BASE: Final[str] = "1rem"
TYPOGRAPHY_SIZE_LG: Final[str] = "1.125rem"
TYPOGRAPHY_SIZE_XL: Final[str] = "1.25rem"
TYPOGRAPHY_SIZE_2XL: Final[str] = "1.5rem"
TYPOGRAPHY_SIZE_3XL: Final[str] = "1.875rem"
TYPOGRAPHY_SIZE_4XL: Final[str] = "2.25rem"
TYPOGRAPHY_SIZE_5XL: Final[str] = "3rem"
TYPOGRAPHY_WEIGHT_REGULAR: Final[str] = "400"
TYPOGRAPHY_WEIGHT_MEDIUM: Final[str] = "500"
TYPOGRAPHY_WEIGHT_SEMIBOLD: Final[str] = "600"
TYPOGRAPHY_WEIGHT_BOLD: Final[str] = "700"
SPACING_0: Final[str] = "0"
SPACING_1: Final[str] = "0.25rem"
SPACING_2: Final[str] = "0.5rem"
SPACING_3: Final[str] = "0.75rem"
SPACING_4: Final[str] = "1rem"
SPACING_6: Final[str] = "1.5rem"
SPACING_8: Final[str] = "2rem"
SPACING_12: Final[str] = "3rem"
SPACING_16: Final[str] = "4rem"
SPACING_24: Final[str] = "6rem"
LAYOUT_MAX_WIDTH_CONTENT: Final[str] = "72rem"
LAYOUT_MAX_WIDTH_PROSE: Final[str] = "40rem"
RADIUS_SM: Final[str] = "4px"
RADIUS_MD: Final[str] = "6px"
RADIUS_LG: Final[str] = "8px"
RADIUS_XL: Final[str] = "12px"
RADIUS_FULL: Final[str] = "9999px"
SHADOW_XS: Final[str] = "0 1px 2px rgba(0,0,0,0.04)"
SHADOW_SM: Final[str] = "0 1px 3px rgba(0,0,0,0.06), 0 1px 2px rgba(0,0,0,0.04)"
SHADOW_MD: Final[str] = "0 4px 6px rgba(0,0,0,0.05), 0 2px 4px rgba(0,0,0,0.04)"
MOTION_DURATION_FAST: Final[str] = "120ms"
MOTION_DURATION_NORMAL: Final[str] = "200ms"
MOTION_EASING_OUT: Final[str] = "cubic-bezier(0.16, 1, 0.3, 1)"
